"""Add home and away recent form features

Revision ID: 035a8913e946
Revises: 587811affc17
Create Date: 2026-09-08 09:50:52.042922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035a8913e946'
down_revision: Union[str, Sequence[str], None] = '587811affc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_features', sa.Column('home_wins_last_5', sa.Integer(), nullable=True))
    op.add_column('team_game_features', sa.Column('home_losses_last_5', sa.Integer(), nullable=True))
    op.add_column('team_game_features', sa.Column('home_win_pct_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('home_avg_points_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('home_avg_points_allowed_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('home_recent_point_diff', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('away_wins_last_5', sa.Integer(), nullable=True))
    op.add_column('team_game_features', sa.Column('away_losses_last_5', sa.Integer(), nullable=True))
    op.add_column('team_game_features', sa.Column('away_win_pct_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('away_avg_points_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('away_avg_points_allowed_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('away_recent_point_diff', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_features', 'away_recent_point_diff')
    op.drop_column('team_game_features', 'away_avg_points_allowed_last_5')
    op.drop_column('team_game_features', 'away_avg_points_last_5')
    op.drop_column('team_game_features', 'away_win_pct_last_5')
    op.drop_column('team_game_features', 'away_losses_last_5')
    op.drop_column('team_game_features', 'away_wins_last_5')
    op.drop_column('team_game_features', 'home_recent_point_diff')
    op.drop_column('team_game_features', 'home_avg_points_allowed_last_5')
    op.drop_column('team_game_features', 'home_avg_points_last_5')
    op.drop_column('team_game_features', 'home_win_pct_last_5')
    op.drop_column('team_game_features', 'home_losses_last_5')
    op.drop_column('team_game_features', 'home_wins_last_5')
    # ### end Alembic commands ###
