"""add is back to back feature

Revision ID: 24d716f408bf
Revises: 7ba487a27593
Create Date: 2026-09-08 09:15:58.304584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d716f408bf'
down_revision: Union[str, Sequence[str], None] = '7ba487a27593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "team_game_features",
    sa.Column(
        "is_back_to_back",
        sa.Boolean(),
        nullable=False,
        server_default=sa.false(),
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_features', 'is_back_to_back')
    # ### end Alembic commands ###
