"""Create game features table

Revision ID: 3ebd3955d99b
Revises: 8c6fe3340864
Create Date: 2026-09-08 10:46:17.241468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebd3955d99b'
down_revision: Union[str, Sequence[str], None] = '8c6fe3340864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('offensive_rating_diff', sa.Float(), nullable=True),
    sa.Column('defensive_rating_diff', sa.Float(), nullable=True),
    sa.Column('net_rating_diff', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_features')
    # ### end Alembic commands ###
