"""add recent form features

Revision ID: 587811affc17
Revises: 24d716f408bf
Create Date: 2026-09-08 09:34:43.830278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587811affc17'
down_revision: Union[str, Sequence[str], None] = '24d716f408bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_features', sa.Column('wins_last_5', sa.Integer(), nullable=True))
    op.add_column('team_game_features', sa.Column('losses_last_5', sa.Integer(), nullable=True))
    op.add_column('team_game_features', sa.Column('win_pct_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('avg_points_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('avg_points_allowed_last_5', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('recent_point_diff', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_features', 'recent_point_diff')
    op.drop_column('team_game_features', 'avg_points_allowed_last_5')
    op.drop_column('team_game_features', 'avg_points_last_5')
    op.drop_column('team_game_features', 'win_pct_last_5')
    op.drop_column('team_game_features', 'losses_last_5')
    op.drop_column('team_game_features', 'wins_last_5')
    # ### end Alembic commands ###
