"""Add efficiency features

Revision ID: c3326f4fd262
Revises: 035a8913e946
Create Date: 2026-09-08 10:21:42.475675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3326f4fd262'
down_revision: Union[str, Sequence[str], None] = '035a8913e946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_game_features', sa.Column('possessions', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('offensive_rating', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('defensive_rating', sa.Float(), nullable=True))
    op.add_column('team_game_features', sa.Column('net_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_game_features', 'net_rating')
    op.drop_column('team_game_features', 'defensive_rating')
    op.drop_column('team_game_features', 'offensive_rating')
    op.drop_column('team_game_features', 'possessions')
    # ### end Alembic commands ###
