"""create team game stats table

Revision ID: de58cb401259
Revises: 8935a0f003cf
Create Date: 2026-09-07 18:54:54.734021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de58cb401259'
down_revision: Union[str, Sequence[str], None] = '8935a0f003cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_abbreviation', sa.String(length=10), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=False),
    sa.Column('fga', sa.Integer(), nullable=False),
    sa.Column('fg_pct', sa.Float(), nullable=False),
    sa.Column('fg3m', sa.Integer(), nullable=False),
    sa.Column('fg3a', sa.Integer(), nullable=False),
    sa.Column('fg3_pct', sa.Float(), nullable=False),
    sa.Column('ftm', sa.Integer(), nullable=False),
    sa.Column('fta', sa.Integer(), nullable=False),
    sa.Column('ft_pct', sa.Float(), nullable=False),
    sa.Column('oreb', sa.Integer(), nullable=False),
    sa.Column('dreb', sa.Integer(), nullable=False),
    sa.Column('reb', sa.Integer(), nullable=False),
    sa.Column('ast', sa.Integer(), nullable=False),
    sa.Column('stl', sa.Integer(), nullable=False),
    sa.Column('blk', sa.Integer(), nullable=False),
    sa.Column('tov', sa.Integer(), nullable=False),
    sa.Column('pf', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_game_stats')
    # ### end Alembic commands ###
